name: Deploy HTML to GitHub Pages

on:
  push:
    branches:
      - main  # deploy whenever code is pushed to main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the repo
      - name: Checkout Repository
        uses: actions/checkout@v3

      # 2. Upload HTML file(s) as artifact for GitHub Pages
      - name: Upload HTML
        uses: actions/upload-pages-artifact@v1
        with:
          path: .  # path to your HTML file(s), "." means the root of repo

      # 3. Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
