name: Deploy HTML to GitHub Pages

on:
  push:
    branches:
      - main  # Trigger deployment on push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Step 2: Upload HTML file(s) as artifact
      - name: Upload HTML Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: .  # Upload all files in the root directory

      # Step 3: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        id: deployment
        permissions:
          pages: write  # Grant permission to deploy to Pages
          id-token: write  # Grant permission to verify deployment origin
        environment:
          name: github-pages
          url: ${{ steps.deployment.outputs.page_url }}

